---

- name: Install necessary software on all hosts
  tags: setup
  hosts: all
  become: true

  tasks:
  - name: Update cache
    apt:
      update_cache: yes

  - name: Install network time tools
    apt:
      name: chrony
      state: latest

  - name: Install Python3 and pip
    apt:
      name:
        - python3
        - python3-pip
  - name: Upgrade pip & setuptools
    pip:
      name:
        - pip
        - setuptools
      state: latest
  - name: Install pip packages
    pip:
      name:
        - logging==0.4.9.6
        - asyncio


- name: Install necessary software on players
  tags: setup
  hosts: players
  become: true

  tasks:
  - name: Install I2C tools and Python interfaces for SPI and GPIO
    apt:
      name:
        - i2c-tools
        - python3-spidev
        - python3-rpi.gpio
      state: latest
  - name: Install I2C interface tools
    apt:
      state: latest

  - name: Install pip package for the LED lights
    pip:
      name:
        - adafruit-ws2801

