---

- name: Make sure the correct software and config is setup for time synchronisation
  tags: setup
  hosts: players
  become: true

  tasks:

  - name: Make sure there are no conflicting packages
    apt:
      name:
        - ntp
        - ntpd
        - ntpstat
        - ntpdate
      state: absent
      purge: yes
      autoremove: yes
  - name: Make sure the chrony package is installed
    apt:
      name: chrony
      state: latest

  - name: Copy chrony.conf
    copy:
      src: etc/chrony/chrony.conf
      dest: /etc/chrony/
      owner: root
      group: root
      mode: 0644


- name: Synchronise clocks of all players
  tags: setup, experiment
  hosts: players
  become: true

  vars:
    TIMEZONE: "Europe/London"

  tasks:

  - name: Change timezone
    shell: "raspi-config nonint do_change_timezone {{ TIMEZONE }}"

  - name: Start NTP service
    shell: "systemctl start chronyd"

  - name: Fetch time and correct any offsets
    shell: "chronyc tracking; chronyc makestep"

  - name: Sync hwclock with system clock
    shell: hwclock -w


- name: Get date and time and service status
  hosts: players

  tasks:
  - name: Get timedatectl status and timestamp from the system
    shell: "timedatectl status && date +%Y-%m-%d%H-%M-%S.%2N"
    register: timestat
  - name: Print system time and status
    debug:
      var: timestat.stdout_lines
