---

- name: copy LED control code on all players
  tags: setup
  hosts: players

  tasks:

  - name: Create synch folder
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - '/home/pi/synch'
      - '/home/pi/logs'
  - name: Copy LED light control Python scripts
    copy:
      src: "{{ item }}"
      dest: /home/pi/synch
      owner: pi
      group: pi
      mode: 0644
    with_fileglob: leds/*

