---

- name: Turn on pilot
  tags: test, pilot
  hosts: players

  tasks:
  - name: Turn on pilot
    shell:
      cmd: python3 startup.py
      chdir: /home/pi/synch

- name: Run WS2801 example
  tags: test, now
  hosts: players

  tasks:
  - name: Run WS2801 example
    shell:
      cmd: python3 ws2801_example.py
      chdir: /home/pi/synch


- name: Run mock loop example
  tags: test, schedule
  hosts: players

  tasks:
  - name: Add cron job
    cron:
      name: "synch-loop-test-{{ MINUTE }}"
      minute: "{{ MINUTE }}"
      job: 'while [ "10" -gt "$(date +\%S)" ]; do /bin/sleep 0.1; done; python3 /home/pi/synch/mockloop.py'

- name: Stop mock loop example
  tags: test, stop
  hosts: players

  tasks:
  - name: Delete cron job
    cron:
      name: "synch-loop-test-{{ MINUTE }}"
      minute: "{{ MINUTE }}"
      state: absent

  - name: Stop process
    become: true
    shell: "pkill -f mockloop"
    ignore_errors: yes

  - name: Turn off leds
    shell: "python3 /home/pi/synch/stop.py"

